name: dart_edge_sample
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  cf_workers: ^1.0.0-rc.1
  fetch_api: ^2.2.0
  http: ^1.2.2
  supabase: ^2.3.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
